services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cwa_app
      POSTGRES_PASSWORD: "_Q7xIu5szfoK3BfOuLapqEd16PWJjztP"
    volumes:
      - cwa_app_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "2OgM7t_p_2-qSG95uXkI08eMC18mkPfv"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cwa_app_test
      POSTGRES_PASSWORD: "-7SVc6WIxfSjfrLVvZB5D_cc90Kt5-BW"
    volumes:
      - cwa_app_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "L62E-3-rTMywwdzGqhE9oRdfvlnPL-V6"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  cwa_app_data:
  cwa_app_test_data:
